# Generated by Django 4.1.7 on 2023-04-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='contact',
            new_name='phone',
        ),
    ]
